#include "CollectivesPassesCliImpl.h"
#include "CollectivesSpmdSubPartitionerImpl.h"
#include "CompleteCollectivesSpmdSubPartitionImpl.h"
#include "MoveDeviceDomainToFrontendAttributesImpl.h"
#include "SetCollectivesDeviceDomainImpl.h"
